version: "3.9"
services:
  easywa-db:
    container_name: easywa-db
    image: mongo:5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=easywa
      - MONGO_INITDB_USERNAME=easywa
      - MONGO_INITDB_PASSWORD=secret
    ports:
      - "27071:27017"
    networks:
      - jktasia-network
    volumes:
      - ./scripts/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh:ro
      - easywa-db:/data/db

volumes:
  easywa-db:

networks:
  jktasia-network:
    external: true